### ISSUE TITLE
Defect prediction replication in CI pipeline

### ISSUE THREAD

**Issue by AlexSpart** [radon-h2020/radon-defect-predictor#2]
DPT is meant to be used straight from IDE but also in an automated manner inside a CI/CD pipeline. 
In https://radon-h2020.github.io/radon-defect-prediction-api/ is described how to use DPT using it as a docker container, by accessing its API. Although this functionality has been tested successfully passing a standalone file to the API calls, the  possibility of passing the whole csar file as input to the DPT has not been implemented, and therefore additional steps of file handling have to be added. 

Could you provide information on how to access and identify the files inside the csar structure that makes sense to be tested for defects in an automated manner? Practically, how the defect prediction plugin performs this functionality.

***Enchancement***
Similarly to the DPT plugin in IDE, where we invoke the prediction to a csar archive and we receive defects analysis for each tosca file inside it, it is desired to have the same functionality when running DPT using the containerized version, by just providing the csar deployment package.

**Comment by stefanodallapalma** [comment]
@AlexSpart ok, I ve moved this issue to https://github.com/radon-h2020/radon-defect-predictor and I will close it once the feature is ready. So you'll get notified.
