### ISSUE TITLE
DPT-cli in Jenkins pipeline issue

### ISSUE THREAD

**Issue by AlexSpart** [radon-h2020/radon-defect-predictor#3]
Hi Stefano,
I am testing the DPT cli in a Jenkins pipeline where I get this error.

```
Collecting repository-scorer~=0.2.0 (from -r requirements.txt (line 7))
Could not find a version that satisfies the requirement repository-scorer~=0.2.0 (from -r requirements.txt (line 7)) (from versions: )
No matching distribution found for repository-scorer~=0.2.0 (from -r requirements.txt (line 7))
```
 
I am using pip3 as python2 (which is default for CentOS 7) has other problems with ansiblemetrics installation..
Which python version is DPT bound to? 

(ps. DPT-cli works flawlessly on my local machine using python3)

**Comment by stefanodallapalma** [comment]
@AlexSpart what version of Python are you using on Jenkins?

**Comment by AlexSpart** [comment]
The Jenkins Instance is bound to Python 3.6.8 atm.

**Comment by stefanodallapalma** [comment]
I updated the minimum version of repository-scorer to 3.6.
Install the new radon-defect-predictor version 0.2.1 (https://pypi.org/project/radon-defect-predictor/) and let me know if it solves the problem.
If so, please close the issue.

**Comment by AlexSpart** [comment]
Thank you for the rapid reaction @stefanodallapalma , that solves the issue!
