### ISSUE TITLE
R-T3.4-6: The defect-prediction tool must provide built-in functionalities to be able to communicate with infrastructure elements in an automatic fashion. 

### ISSUE THREAD

**Issue by dardin88** [radon-h2020/radon-defect-predictor#4]
ID | R-T3.4-6
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | FUNCTIONAL_SUITABILITY
User Story | As an Operations Engineer I want the tool to be used automatically by my architecture's elements, such as an orchestrator
Requirement | The defect-prediction tool must provide built-in functionalities to be able to communicate with infrastructure elements in an automatic fashion. In order for automation, the DPT needs to be scriptable. Either through an api or a CLI.
Extended Description | An orchestrator should be able to use this tool in an automatic manner to check the deployment model for defects before starting the deployment?
Priority | Must have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | Direct implementation on IDE, feature checklist, case-study
Dependency | [R-T3.4-3](https://github.com/radon-h2020/radon-defect-prediction-api/issues/3), https://github.com/radon-h2020/radon-defect-predictor/issues/2

**Comment by stefanodallapalma** [comment]
The DPT is available as a [PyPI package](https://pypi.org/project/radon-defect-predictor/) to be integrated into Python applications.
It is also available as a [Docker image](https://hub.docker.com/repository/docker/radonconsortium/repo-miner) to execute the command-line-interface within a Docker container (on any machine supporting Docker) and be integrated in CI/CD pipelines (e.g., Jenkins).

See [README](https://github.com/radon-h2020/radon-defect-prediction-cli/blob/main/README.md) and the [DOCS](https://radon-h2020.github.io/radon-defect-prediction-cli/) for more information. 

Closing. 
@gcasale
