### ISSUE TITLE
Using DPT docker image

### ISSUE THREAD

**Issue by AlexSpart** [radon-h2020/radon-defect-predictor#5]
Hi, 
I am trying to use the DPT in a CI pipeline that runs on CentOS 7. 
Following the documentation, first I am trying to download a pre-trained model to use for my prediction using the following command:
` docker run -v /tmp/radon-dp-volume:/app radon-dp:latest radon-defect-predictor download-model tosca github AlexSpart/radon-csar`

DPT responds that the arguement "path_to_repository" is required even though I specify it as you can see above.
What is the proper definition of this command? Any examples?

<img width="940" alt="Screenshot 2020-12-12 at 15 36 58" src="https://user-images.githubusercontent.com/23174477/101986821-9fddc300-3c90-11eb-9af6-ed8a46935123.png">

**Comment by stefanodallapalma** [comment]
Hi,
It seems that you are using an out-of-date image: `repository_full_name_or_id` and `path_to_repository` were replaced by a single argument `repository`. So, the command is correct, but you are using it on the wrong tool's version.
Can you do `docker pull radonconsortium/radon-dp` again, and let me know whether it now works?

**Comment by AlexSpart** [comment]
Hi Stefano,
I did a fresh pull of the `radonconsortium/radon-dp` image, the response is the same as above.
`Digest: sha256:77d1f6108ce0debecd524931513e0412479b9f887d35ecb53c743b29d9ea11df`

**Comment by stefanodallapalma** [comment]
After pulling, did you run the command with `radonconsortium/radon-dp` or `radon-dp`? 
Those are two different images.

Can you ran `docker run radonconsortium/radon-dp radon-defect-predictor download-model -h` and check if you get the same output?

```
~$ docker pull radonconsortium/radon-dp
Using default tag: latest
latest: Pulling from radonconsortium/radon-dp
Digest: sha256:77d1f6108ce0debecd524931513e0412479b9f887d35ecb53c743b29d9ea11df
Status: Downloaded newer image for radonconsortium/radon-dp:latest
docker.io/radonconsortium/radon-dp:latest

~$ docker run radonconsortium/radon-dp radon-defect-predictor download-model -h
usage: radon-defect-predictor download-model [-h]
       {ansible,tosca} {github,gitlab}
       repository

positional arguments:
  {ansible,tosca}  the language the model is trained on
  {github,gitlab}  the platform the user's repository is hosted to
  repository       the user's remote repository in the form
                   <namespace>/<repository> (e.g., radon-h2020/radon-defect-
                   prediction-cli)

optional arguments:
  -h, --help       show this help message and exit

```

**Comment by AlexSpart** [comment]
Ok, it works with `radonconsortium/radon-dp` . 
Didn't realize there were 2 different images from different publishers! 
I guess I should delete the radon-dp image?

**Comment by stefanodallapalma** [comment]
Yes. Either you (1) delete the `radon-dp` image, or (2) rename the `radonconsortium/radon-dp` to `radon-dp`.
I would recommend option (1).

**Comment by AlexSpart** [comment]
Alright! Thanks for catching this!
